export const categoryList = [
    {
        id: 1,
        image: "./images/fashion.png",
        value: 'fashion' ,
        label: 'Fashion',
    },
    {
        id: 2,
        image: "./images/mobile.png",
        value: 'mobiles',
        label: 'Mobiles',
    },
    {
        id: 3,
        image: "./images/electronic.png",
        value: 'electronics',
        label: 'Electronics',
    },
    {
        id: 4,
        image: "./images/home.png",
        value: 'home',
        label: 'Home',
    },
    {
        id: 5,
        image: "./images/appliance.png",
        value: 'appliances',
        label: 'Appliances',
    },
    {
        id: 6,
        image: "./images/personalcare.png",
        value: 'personalCare',
        label: 'Personal Care',
    },
    {
        id: 7,
        image: "./images/toy.png",
        value: 'toys',
        label: 'Toys & Baby',
    },
    {
        id: 8,
        image: "./images/furniture.png",
        value: 'furniture',
        label: 'Furniture',
    },
    {
        id: 9,
        image: "./images/sports.png",
        value: 'sports',
        label: 'Sports',
    },
    {
        id: 10,
        image: "./images/grocery.png",
        value: 'grocery',
        label: 'Grocery',
    },
    {
        id: 11,
        image: "./images/nutrition.png",
        value: 'nutrition',
        label: 'Nutrition & More',
    },
    {
        id: 12,
        image: "./images/vehicle.png",
        value: 'vehicle',
        label: 'Bikes & Cars',
    },
];

const ListItems = [
    {
        id:1,
        title:"NIKE FOOTWEAR",
        price:200,
        image:'/images/nikeShoe.jpg',
        rating:4,
        description:"Running Collection ",
        category: 'fashion',
    },
     {
        id:2,
        title:"ANNIE GLASSES",
        price:200,
        image:"./images/annie-williams-Glasses.jpg",
        rating:4,
        description:"Running Collection",
        category: 'fashion',
    },
     {
        id:3,
        title:"ANOMALY TSHIRT",
        price:200,
        image:"./images/anomalyTshirt.jpg",
        rating:4,
        description:"Running Collection",
        category: 'fashion',
    },
     {
        id:4,
        title:"FABIAN WATCH",
        price:200,
        image:"./images/fabian-heimann-watch.jpg",
        rating:4,
        description:"Running Collection",
        category: 'fashion',
    },
        {
        id:5,
        title:"IRENE BAG",
        price:200,
        image:"./images/irene-kredenets-Bag.jpg",
        rating:4,
        description:"Running Collection",
        category: 'fashion',
    },
        {
        id:6,
        title:"LAURA BAG",
        price:200,
        image:"./images/laura-chouette-Bag.jpg",
        rating:4,
        description:"Running Collection",
        category: 'fashion',
    },
        {
        id:7,
        title:"HUAWAI PHONE",
        price:200,
        image:"./images/huawaiPhone.jpg",
        rating:4,
        description:"Running Collection",
        category: 'mobile',
    },
        {
        id:8,
        title:"IPHONE XR",
        price:200,
        image:"./images/iphoneXr.jpg",
        rating:4,
        description:"Running Collection",
        category: 'fashion',
    },
        {
        id:9,
        title:"DELL LAPTOP",
        price:200,
        image:"./images/dellLaptop.jpg",
        rating:4,
        description:"Running Collection",
        category: 'electronic',
    },
        {
        id:10,
        title:"MAARTRN FLOWERPOT",
        price:200,
        image:"./images/maarten-flowerpot.jpg",
        rating:4,
        description:"Running Collection",
        category: 'home',
    },
        {
        id:11,
        title:"KHLOE CUSHION",
        price:200,
        image:"./images/khloe-cushion.jpg",
        rating:4,
        description:"Running Collection",
        category: 'home',
    },
        {
        id:12,
        title:"COLLOV SWING",
        price:200,
        image:"./images/collov-swing.jpg",
        rating:4,
        description:"Running Collection",
        category: 'home',
    },
        {
        id:13,
        title:"KHAJONKIET MIXER",
        price:200,
        image:"./images/khajonkiet-mixer.jpg",
        rating:4,
        description:"Running Collection",
        category: 'appliance',
    },
    {
        id:14,
        title:"HOUSE CHIMNEY",
        price:200,
        image:"./images/house-chimney.jpg",
        rating:4,
        description:"Running Collection",
        category: 'appliance',
    },
        {
        id:15,
        title:"PLANET WASHING M/S",
        price:200,
        image:"./images/planetcare-washing.jpg",
        rating:4,
        description:"Running Collection",
        category: 'appliance',
    },
        {
        id:16,
        title:"DANIEL MIXER",
        price:200,
        image:"./images/daniel-mixer.jpg",
        rating:4,
        description:"Running Collection",
        category: 'appliance',
    },
        {
        id:17,
        title:"KATERYNA CREAM",
        price:200,
        image:"./images/kateryna-cream.jpg",
        rating:4,
        description:"Running Collection",
        category: 'personalcare',
    },
        {
        id:18,
        title:"APOTHECARY SHAMPOO",
        price:200,
        image:"./images/apothecary-shampoo.jpg",
        rating:4,
        description:"Running Collection",
        category: 'personalcare',
    },
        {
        id:19,
        title:"AKSHIKA GEL",
        price:200,
        image:"./images/akshika-gel.jpg",
        rating:4,
        description:"Running Collection",
        category: 'personalcare',
    },
        {
        id:20,
        title:"HUMBLE TOOTHBRUSH",
        price:200,
        image:"./images/humble-toothbrush.jpg",
        rating:4,
        description:"Running Collection",
        category: 'personalcare',
    },
        {
        id:21,
        title:"KARLY LIPSTICK",
        price:200,
        image:"./images/karly-lipstick.jpg",
        rating:4,
        description:"Running Collection",
        category: 'personalcare',
    },
        {
        id:22,
        title:"PURE NAILPAINT",
        price:200,
        image:"./images/pure-nailpaint.jpg",
        rating:4,
        description:"Running Collection",
        category: 'personalcare',
    },
        {
        id:23,
        title:"JERRY TOY",
        price:200,
        image:"./images/jerry-toy.jpg",
        rating:4,
        description:"Running Collection",
        category: 'toy',
    },
        {
        id:24,
        title:"JOSE TOY",
        price:200,
        image:"./images/jose-toy.jpg",
        rating:4,
        description:"Running Collection",
        category: 'toy',
    },
        {
        id:25,
        title:"FERNANDO TOY",
        price:200,
        image:"./images/fernando-toy.jpg",
        rating:4,
        description:"Running Collection",
        category: 'toy',
    },
        {
        id:26,
        title:"GIORGIO TOY",
        price:200,
        image:"./images/giorgio-toy.jpg",
        rating:4,
        description:"Running Collection",
        category: 'toy',
    },
          {
        id:27,
        title:"DECONOVO BED",
        price:200,
        image:"./images/deconovo-bed.jpg",
        rating:4,
        description:"Running Collection",
        category: 'furniture',
    },
            {
        id:28,
        title:"KENNY BED",
        price:200,
        image:"./images/kenny-bed.jpg",
        rating:4,
        description:"Running Collection",
        category: 'furniture',
    },
            {
        id:29,
        title:"SUCHIT CHAIR",
        price:200,
        image:"./images/suchit-chair.jpg",
        rating:4,
        description:"Running Collection",
        category: 'furniture',
    },
            {
        id:30,
        title:"PHILLIP SOFA",
        price:200,
        image:"./images/phillip-sofa.jpg",
        rating:4,
        description:"Running Collection",
        category: 'furniture',
    },
                {
        id:31,
        title:"SKETING",
        price:200,
        image:"./images/sketing.jpg",
        rating:4,
        description:"Running Collection",
        category: 'sports',
    },
                   {
        id:32,
        title:"BASKETBALL",
        price:200,
        image:"./images/basketball.jpg",
        rating:4,
        description:"Running Collection",
        category: 'sports',
    },
                   {
        id:33,
        title:"TENNIS",
        price:200,
        image:"./images/tennis.jpg",
        rating:4,
        description:"Running Collection",
        category: 'sports',
    },
                   {
        id:34,
        title:"FOOTBALL",
        price:200,
        image:"./images/football.jpg",
        rating:4,
        description:"Running Collection",
        category: 'sports',
    },
                    {
        id:35,
        title:"BROCCOLI",
        price:200,
        image:"./images/broccoli.jpg",
        rating:4,
        description:"Running Collection",
        category: 'grocery',
    },
                    {
        id:36,
        title:"EGG",
        price:200,
        image:"./images/egg.jpg",
        rating:4,
        description:"Running Collection",
        category: 'grocery',
    },
                     {
        id:37,
        title:"GINA SUPLEMENT",
        price:200,
        image:"./images/gina-supliment.jpg",
        rating:4,
        description:"Running Collection",
        category: 'nutrition',
    },
                       {
        id:38,
        title:"MUSTANG GT",
        price:200,
        image:"./images/mustang-gt.jpg",
        rating:4,
        description:"Running Collection",
        category: 'vehicle',
    },                   {
        id:39,
        title:"MERCEDES BENZ",
        price:200,
        image:"./images/mercedes-benz.jpg",
        rating:4,
        description:"Running Collection",
        category: 'vehicle',
    },                   {
        id:40,
        title:"SUZUKI GSX",
        price:200,
        image:"./images/suzuki-gsx.jpg",
        rating:4,
        description:"Running Collection",
        category: 'vehicle',
    },

     
]
export default ListItems;